# Intro to Pandas

In [1]:
import pandas as pd 
import numpy as np

In [2]:
# Create panda series 
# Series is strictly one dimentional 
data = [1,2,3,4,5,6]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
data = [1,2,3,4,5,6]
series = pd.Series(data,index=["idx","idx","idx3","cidx","idx5","idx6"])
series

idx     1
idx     2
idx3    3
cidx    4
idx5    5
idx6    6
dtype: int64

# Pandas Dataframe

In [4]:
# Create pandas dataframe from csv 
test_df = pd.read_csv("test.csv")
test_df.head(5)

  Name   Age
0     A    15
1     B    15
2     C    15
3     D    15
4     E    15

In [5]:
print(test_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      object
 1   Age     9 non-null      int64
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes
None

In [6]:
test_df.describe()

       Age
count   9.0
mean   15.0
std     0.0
min    15.0
25%    15.0
50%    15.0
75%    15.0
max    15.0

In [7]:
test_df.columns

Index(['Name ', 'Age '], dtype='object')

In [8]:
data = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
df = pd.DataFrame(data=data,columns=['col1','col2','col3','col4','col5','col6'],dtype='float64')
df

   col1  col2  col3  col4  col5  col6
0   1.0   2.0   3.0   4.0   5.0   6.0
1   7.0   8.0   9.0  10.0  11.0  12.0

In [9]:
# Print rows 
print(df.loc[0])

col1    1.0
col2    2.0
col3    3.0
col4    4.0
col5    5.0
col6    6.0
Name: 0, dtype: float64

In [10]:
# Print columns
print(df['col1'])

0    1.0
1    7.0
Name: col1, dtype: float64

In [11]:
len(df)

2

In [12]:
df.loc[len(df)] = [13,14,15,16,17,18]

print(df)

   col1  col2  col3  col4  col5  col6
0   1.0   2.0   3.0   4.0   5.0   6.0
1   7.0   8.0   9.0  10.0  11.0  12.0
2  13.0  14.0  15.0  16.0  17.0  18.0

In [13]:
df["col7"] = [-1,-2,-2]
df

   col1  col2  col3  col4  col5  col6  col7
0   1.0   2.0   3.0   4.0   5.0   6.0    -1
1   7.0   8.0   9.0  10.0  11.0  12.0    -2
2  13.0  14.0  15.0  16.0  17.0  18.0    -2

In [14]:
# Drop or delete rows or columns 
# Axis =0 for rows and axis=1 for colums
# df.drop(0,axis=0)

In [15]:
# slicing dataframe 
df[0:2]

   col1  col2  col3  col4  col5  col6  col7
0   1.0   2.0   3.0   4.0   5.0   6.0    -1
1   7.0   8.0   9.0  10.0  11.0  12.0    -2

In [16]:
df.loc[0,'col2'] = np.nan
df

   col1  col2  col3  col4  col5  col6  col7
0   1.0   NaN   3.0   4.0   5.0   6.0    -1
1   7.0   8.0   9.0  10.0  11.0  12.0    -2
2  13.0  14.0  15.0  16.0  17.0  18.0    -2

In [17]:
df.isna()

    col1   col2   col3   col4   col5   col6   col7
0  False   True  False  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False

In [18]:
data = {"employee_name" : ["a","b","c","d","e","f"],"dept" : ["dept1","dept3","dept1","dept1","dept1","dept3"],"salary" : ["100000","500000","150000","145000","150000","600000"]}
df =pd.DataFrame(data=data)
df

  employee_name   dept  salary
0             a  dept1  100000
1             b  dept3  500000
2             c  dept1  150000
3             d  dept1  145000
4             e  dept1  150000
5             f  dept3  600000

In [19]:
# test = df[["dept","salary"]].groupby(["dept"]).mean()
# test

In [20]:
l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
df = pd.DataFrame(l, columns=["a", "b", "c"])
df

   a    b  c
0  1  2.0  3
1  1  NaN  4
2  2  1.0  3
3  1  2.0  2

In [21]:
df.groupby(by=["b"]).sum()

     a  c
b
1.0  2  3
2.0  2  5

In [22]:
# def custom_agg(x):
#     return x.a/x.c

# custom_df = df.agg(custom_agg)